name: Discord Notification

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SLACK_MESSAGE: |
            🔔 **${{ github.actor }}** a pushé sur **${{ github.ref_name }}**
            📄 `${{ github.event.head_commit.message }}`
