name: Discord Notification

on:
  push:
    branches:
      - main
      - dev
      - romain
      - nathan
  pull_request:
    branches:
      - main
      - dev
      - romain
      - nathan
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          AUTHOR="${{ github.actor }}"
          BRANCH="${{ github.ref_name }}"
          
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🔔 **$AUTHOR** a pushé sur **$BRANCH** : \`$COMMIT_MESSAGE\`\"}" \
          $DISCORD_WEBHOOK
